---

- name: update repo
  hosts: all
  become: true
  pre_tasks:

  - name: update all
    apt:
     update_cache: yes
    when: ansible_distribution == "Debian"
   

- name: create ngnix reverse proxy
  hosts: nginx
  become: true

  roles:
    - reverse-proxy

#  post_tasks:
#    - name: install content from local file
#      copy:
#        src: files/html/index.html
#        dest: /var/www/html/index.html
#      changed_when: true
#      notify: restart nginx
