---
# tasks file for reverse-proxy

- name: install nginx
  package:
    name: "{{ nginx_package }}"
    state: latest
    update_cache: yes

- name: install vhost config file
  template:
    src: vhost.conf.j2
    dest: /etc/nginx/sites-available/{{ server_name }}.conf
    owner: root
    group: root
    mode: 0644
